/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Check if native audio capture is available (i.e., an input device exists). */
export declare function isNativeAudioAvailable(): boolean
/**
 * Start recording from the default input device.
 * `on_data` receives PCM i16 LE chunks as Buffer.
 * `on_end` is called if the stream ends unexpectedly.
 * Returns true if recording started successfully.
 */
export declare function startNativeRecording(onData: (arg: Buffer) => any, onEnd: () => any): boolean
/** Stop the current recording. */
export declare function stopNativeRecording(): void
/** Check if recording is currently active. */
export declare function isNativeRecordingActive(): boolean
/** Start audio playback on the default output device. */
export declare function startNativePlayback(sampleRate: number, channels: number): boolean
/** Write PCM i16 LE data to the playback buffer. */
export declare function writeNativePlaybackData(data: Buffer): boolean
/** Stop playback. */
export declare function stopNativePlayback(): void
/** Check if playback is active. */
export declare function isNativePlaying(): boolean
/**
 * Returns microphone authorization status.
 * macOS TCC: 0=notDetermined, 1=restricted, 2=denied, 3=authorized.
 * Linux: always 3 (no system-level mic permission API).
 * Windows: 3 if allowed, 2 if denied via registry.
 */
export declare function microphoneAuthorizationStatus(): number
